# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: python_app
spec:
  selector:
    app: python_app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30009
  type: NodePort
